config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :categories, except: %i[update destroy] do
    resources :expenses, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy, class_name: 'CategoryExpense'
  has_many :expenses, through: :category_expenses, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy, class_name: 'CategoryExpense'
  has_many :categories, through: :category_expenses, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :expenses, dependent: :destroy, foreign_key: :author_id
  has_many :categories, dependent: :destroy, foreign_key: :author_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def show
    @category = current_user.categories.find(params[:id])
    @expenses = @category.expenses.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def new
    @expense = Expense.new
    @categories = Category.where(author_id: current_user.id).includes([:author]).order(created_at: :desc)
    @selected_category = Category.find(params[:category_id])
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user

    if @expense.save
      params[:category_ids].each do |id|
        CategoryExpense.create(category_id: id.to_i, expense_id: @expense.id)
      end
      redirect_to category_path(params[:category_id]), notice: 'Transaction added successfully'
    else
      render :new, status: 422
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless current_user

    redirect_to '/categories'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="page">


  <section class="page-navbar-section">
    <div class="page-navbar">
      <div class="bars"><i class="fa-solid fa-bars"></i></div>
      <div class="heading">CATEGORIES</div>
      <div class="search"><i class="fa-solid fa-magnifying-glass"></i></div>
    </div>

    <% if user_signed_in? %>
      <div class="sign-out-btn"> <%= button_to "Log out", '/users/sign_out', method: :delete %> </div>
    <%end%>
  </section>

  <% if @categories.length.positive? %>
    <div class="page-mid-section">
      <% @categories.each do |category| %>
        <%= link_to "/categories/#{category.id}" do %>
          <div class="card-item">
            <div class="card-img-box">
              <img class="card-img" src=<%= category.icon %> alt=<%= category.name %> >
            </div>
            <div class="card-info">
              <p class="card-name"><%= category.name.capitalize %> <p>
              <small class="card-date"><%= category.created_at.strftime('%d-%b-%Y') %></small>
            </div>
            <div class="card-sum">
              <p>$<%= category.expenses.sum('amount') %> <p>
            </div>
          </div>
        <%end%>
      <% end %>
    </div>
  <% else %>
    <p>No Categories created.</p>
  <% end %>

  <div class="add-container">
    <button><%= link_to 'ADD NEW CATEGORY', new_category_path %></button>
  </div>

</div>

app/views/categories/new.html.erb
<div class="page">

  <section class="page-navbar-section">
    <div class="page-navbar">
      <div class="back">
        <%= link_to categories_path do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="heading">NEW CATEGORY</div>
      <div></div>
    </div>
  </section>

  <div class="page-mid-section">
    <% if @category.errors.any? %>
      <div>
        <p><%= pluralize(@category.errors.count, "error") %> found:</p>

        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @category, url: categories_path,  method: :post do | form |%>
    <div>

      <div class="session-field">  
        <%= form.text_field :name, placeholder: 'Name', required: true, class: "session-field-input" %>
      </div>

      <div class="session-field">
        <%= form.text_field :icon, placeholder: 'icon URL', required: true, class: "session-field-input" %>
      </div>

      <div class="save-btn"><%= form.submit 'Save'%></div>
    </div>
    <% end %>
  </div>

</div>

app/views/categories/show.html.erb
<div class="page">

  <section class="page-navbar-section">
    <div class="page-navbar">
      <div class="back">
        <%= link_to categories_path(@category.id) do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="heading">DETAILS</div>
      <div></div>
    </div>

    <p class="detail-header"><%= @category.name %>: $<%= @category.expenses.sum('amount')%></p>
  </section>

  
  <% if @expenses.length.positive? %>
    <div class="page-mid-section">
      <% @expenses.each do |item| %>
        <div>
          <div class="card-item">
            <div class="card-info">
              <p class="card-name"><%= item.name.capitalize %> <p>
              <small class="card-date"><%= item.created_at.strftime('%d-%b-%Y') %></small>
            </div>
            <div class="card-sum">
              <p>$<%= item.amount %><p>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  <% else %>
    <p>No Transactions recorded.</p>
  <% end %>

  <div class="add-container">
    <button><%= link_to 'Add New Transaction', new_category_expense_path(@category.id) %></button>
  </div>

</div>

app/views/expenses/new.html.erb
<div class="page">

  <section class="page-navbar-section">
    <div class="page-navbar">
      <div class="back">
        <%= link_to categories_path do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="heading">NEW TRANSACTION</div>
      <div></div>
    </div>
    <p class="detail-header">( for: <%= @selected_category.name %> )</p>
  </section>

  <div class="page-mid-section">
  
    <% if @expense.errors.any? %>
      <div>
        <p><%= pluralize(@expense.errors.count, "error") %> found:</p>

        <ul>
          <% @expense.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @expense, url: category_expenses_path,  method: :post do | form |%>
      <div>
        <div class="session-field">
          <%= form.text_field :name, placeholder: 'Name', required: true, class: "session-field-input" %>
        </div>

        <div class="session-field">
          <%= form.number_field :amount, placeholder: 'Amount', required: true, class: "session-field-input" %> <br />
        </div>

        <p class="trans-p">Select Categories to add this transaction to:</p>
        <div class="trans-checks">
          <% @categories.each do |category| %>
            <% if category.id == @selected_category.id %>
              <%= hidden_field_tag 'category_ids[]', category.id %>
              <%= check_box_tag 'category_ids[]', category.id, true, disabled: true %>
            <% else %>
              <%= check_box_tag 'category_ids[]', category.id %>
            <% end %>
            <%= category.name %><br>
          <% end %>
        </div>

        <button class="save-btn"><%= form.submit "Save Transaction"%></button>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="splash__container">
  <div class="splash__title"><h1>My Budget App</h1></div>
  <div class="splash__session-btns">
    <%= link_to "LOG IN", new_user_session_path %>  
    <%= link_to "SIGN UP", new_user_registration_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>